DROP TABLE IF EXISTS GRADE;

CREATE TABLE GRADE (
    ID SERIAL PRIMARY KEY,
    STUDENT_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    GRADE NUMERIC(4,2) NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
);
