DROP TABLE IF EXISTS GRADE;

CREATE TABLE GRADE
(
    ID SERIAL PRIMARY KEY,
    STUDENT_ID INTEGER NOT NULL,
    COURSE_ID INTEGER NOT NULL,
    GRADE NUMERIC(5,2) NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID)
);
